### ISSUE TITLE
We should define outsiders.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#7]
From the [blog](https://medium.com/@stevan.blog/the-white-paper-endorses-safe-spaces-for-leaders-and-to-actively-include-people-who-feel-like-41af41fde2f4):

> The white paper endorses safe spaces for leaders and to actively include people who feel like outsiders. Can you define who these outsiders are?

**Comment by stevanlohja** [comment]
**Regarding a Safe Space for Leaders:**
This is a complicated one because a leader generally deals with the most stress. If you have an issue, then you report to your manager for a final decision and that becomes their mistake or accomplishment. As you pass information toward the leader, then to their leader, and the leader of that leader information has to become more complex because of the disconnect of duties. Leaders in safe spaces may risk the reality of what a leader deals with. Safe spaces are absolute truth in leadership. E.g. If you're a platoon captain you're men are dependent on the most competent judgement and a safe space under fire might just get you killed and your men. Also, in a diverse environment everyone may consider a safe space their own expectation. E.g. Some people's safe space is their home, some people's safe space is in the park, but a leader needs to address an ever changing environment. E.g. Adapting to job requirements because some skills just become out-dated. I'd propose a safe space for leaders would be wrong because its social engineering. It's social engineering because it's by design and leaders shouldn't be indoctrinated in a designed space. E.g. you don't draw lines in a public space.

Outsiders is pretty unclear. However, the leadership team should declare who these outsiders are. I'd argue that leaders who feel like outsiders are not leader but confidence building and self knowledge could be tools to turn the outsiders to initiators.

**Comment by chadsansing** [comment]
@acabunoc, do you have a preferred definition or way to explain "outsiders?"

**Comment by acabunoc** [comment]
Interesting discussion!

In the context of a community, an outsider would be anyone not part of that group. 

Quick google search:
<img width="654" alt="screen shot 2018-01-23 at 9 14 01 am" src="https://user-images.githubusercontent.com/617994/35280318-d01b617e-001d-11e8-800d-177e82ba836b.png">

@stevanlohja brings up an interesting case where the leader feels like an outsider. In this case, it sounds like we're defining outsider in terms of the broader society, which might be out of scope when you're talking about a project. But great insights, @stevanlohja! Thanks for sharing

**Comment by stevanlohja** [comment]
Broader Society seems more positive than referring to people whom are outsiders. Who is an example of being part of the "broader" part of society?

**Comment by chadsansing** [comment]
Added this to "What is open?" right after the word "outsiders."

> ... - people outside of a community, organization, or project's perceived boundaries who join a project because of shared expertise, interests, and passions. 

How does this sound?

**Comment by chadsansing** [comment]
Barring any feedback and discussion ahead of 2/2/18, I'll close this issue then ahead of the February OLM white paper beta.

**Comment by chadsansing** [comment]
[Join the beta!](https://medium.com/@chadsansing/join-the-open-leadership-map-beta-582446fb399d)
