### ISSUE TITLE
We should define participation & inclusion separately.

### ISSUE THREAD

**Issue by chadsansing** [mozilla/olm-whitepaper#8]
From the [blog](https://medium.com/@stevan.blog/inclusion-should-be-defined-separately-from-participation-1e2adca1918e):

> Inclusion should be defined separately from participation.

**Comment by stevanlohja** [comment]
**Participation**: Is the act of participating.
**Inclusion**: Is the act of participating based on variables.
Inclusive goals should be defined because designing to include based on race, color, national or ethnic origin, age, religion, disability, sex, sexual orientation, gender identity and expression, or veteran status is a form of discrimination and inter-sectional ideologue.

**Comment by chadsansing** [comment]
@Saallen - let's discuss this as a team during a meeting. I think Mozilla has at least an implicit view of this across D&I, Open Innovation, and our team. Would be great to be consistent.

**Comment by Saallen** [comment]
We could run an open discourse inviting some of those teams in to help unpack and define

**Comment by chadsansing** [comment]
I'm working on a decision log that will help explain why we've grouped participation & inclusion. I'll include language from the decision log in the white paper to provide more context about this decision.

**Comment by chadsansing** [comment]
Added the language under "What is open?" in the white paper.

**Comment by chadsansing** [comment]
Barring any feedback and discussion ahead of 2/2/18, I'll close this issue then ahead of the February OLM white paper beta.

**Comment by chadsansing** [comment]
[Join the beta!](https://medium.com/@chadsansing/join-the-open-leadership-map-beta-582446fb399d)
